services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    command: redis-server
    volumes:
      - redis:/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "bundle exec sidekiq"
    entrypoint: []
    env_file: ".env"
    depends_on:
      - db
      - redis

volumes:
  db:
  redis:
