services:
  web:
    image: video-share-app
    environment:
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: redis://redis:6379/1
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always

  worker:
    image: video-share-app
    command: bundle exec sidekiq
    entrypoint: []
    environment:
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: