services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    command: redis-server
    volumes:
      - redis:/data
  web:
    image: video-share-app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: ecs_application_db
      DB_PORT: 5432
      DB_HOST: db
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  worker:
    image: video-share-app
    command: "bundle exec sidekiq"
    entrypoint: []
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: ecs_application_db
      DB_PORT: 5432
      DB_HOST: db
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    depends_on:
      - db
      - redis

volumes:
  db:
  redis:
